DROP SEQUENCE IF EXISTS generate_profile_id;
DROP SEQUENCE IF EXISTS generate_label_id;
DROP SEQUENCE IF EXISTS generate_member_id;
DROP SEQUENCE IF EXISTS generate_album_id;
DROP SEQUENCE IF EXISTS generate_shopping_cart_id;
DROP SEQUENCE IF EXISTS generate_merch_id;
DROP SEQUENCE IF EXISTS generate_order_id;
DROP SEQUENCE IF EXISTS generate_song_id;
DROP SEQUENCE IF EXISTS generate_group_id;
DROP SEQUENCE IF EXISTS generate_forum_id;

CREATE SEQUENCE IF NOT EXISTS generate_profile_id
MINVALUE 1
MAXVALUE 99999999;

CREATE SEQUENCE IF NOT EXISTS generate_label_id
MINVALUE 1
MAXVALUE 9999;

CREATE SEQUENCE IF NOT EXISTS generate_group_id
MINVALUE 1
MAXVALUE 99999999;

CREATE SEQUENCE IF NOT EXISTS generate_forum_id
MINVALUE 1
MAXVALUE 99999999;

CREATE SEQUENCE IF NOT EXISTS generate_member_id
MINVALUE 1
MAXVALUE 99999999;

CREATE SEQUENCE IF NOT EXISTS generate_album_id
MINVALUE 1
MAXVALUE 99999999;

CREATE SEQUENCE IF NOT EXISTS generate_shopping_cart_id
MINVALUE 1
MAXVALUE 99999999;

CREATE SEQUENCE IF NOT EXISTS generate_merch_id
MINVALUE 1
MAXVALUE 99999999;

CREATE SEQUENCE IF NOT EXISTS generate_order_id
MINVALUE 1
MAXVALUE 999999999999;

CREATE SEQUENCE IF NOT EXISTS generate_song_id
MINVALUE 1
MAXVALUE 999999999999;

CREATE OR REPLACE FUNCTION is_date(date_string TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM date_string::DATE;
    RETURN TRUE;
    EXCEPTION WHEN OTHERS THEN
    RETURN FALSE;
END;$$;